FROM ubuntu:18.04

WORKDIR /workdir

RUN apt update
RUN apt install -yqq build-essential
RUN apt install -yqq sudo
RUN apt install -yqq gcc-aarch64-linux-gnu
RUN apt install -yqq libncurses-dev 
RUN apt install -yqq libyaml-dev 
RUN apt install -yqq flex 
RUN apt install -yqq bison 
RUN apt install -yqq git 
RUN apt install -yqq wget 
RUN apt install -yqq ca-certificates 
RUN apt install -yqq uuid-runtime
